# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: amoiseik <amoiseik@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/01/05 16:20:11 by amoiseik          #+#    #+#              #
#    Updated: 2026/01/05 19:01:03 by amoiseik         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = a.out
CXX = -cpp
CXXFLAGS = -Wextra -Werror -Wall -std=c++98

SRCS = main.cpp Bureaucrat.cpp